_extends: .github
repository:
  name: eslint-config-typescript
  description: shareable ESLint config for TypeScript projects
  homepage: https://npm.im/@form8ion/eslint-config-typescript
  private: false
